# -*- coding: utf-8 -*-
"""analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19swm9ITCYCzutTooVxdQ2VgDyZ2-GY71
"""

import pandas as pd

def get_top_dividend_companies(industry=None):
    df = pd.read_csv("Stock_Data_After_2015.csv")
    if industry:
        df = df[df["Industry_Tag"] == industry]
    result = df.groupby("Brand_Name")["Dividends"].sum().nlargest(5)
    return result.reset_index()

