# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgFjPsAMzJWCqBGwSFPaqmKqX3UbBLDv
"""

from flask import Flask, render_template, request
from analysis import get_top_dividend_companies

app = Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def index():
    summary = None
    if request.method == "POST":
        industry = request.form.get("industry")
        summary = get_top_dividend_companies(industry)
    return render_template("index.html", summary=summary)

if __name__ == "__main__":
    app.run(debug=True)

