# -*- coding: utf-8 -*-
"""test_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pU6fr0Vu2RyTemlWZ2GOr_R1UzcFLC-U
"""

import pandas as pd
from analysis import get_top_dividend_companies

def test_top_dividend_shape():
    result = get_top_dividend_companies()
    assert isinstance(result, pd.DataFrame)
    assert len(result) <= 5

